Forecast_Indian_Stock_Market/urls.py
from django.contrib import admin
from admins import views as admins
from django.urls import path
from users import views as usr
from . import views as mainView

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', mainView.index, name='index'),
    path("UserRegister/", mainView.UserRegister, name="UserRegister"),
    path("AdminLogin/", mainView.AdminLogin, name="AdminLogin"),
    path('index/', mainView.index, name='index'),
    path("UserLogin/", mainView.UserLogin, name="UserLogin"),

    ### User Side Views
    path("UserRegisterActions/", usr.UserRegisterActions, name="UserRegisterActions"),
    path("UserLoginCheck/", usr.UserLoginCheck, name="UserLoginCheck"),
    path("UserHome/", usr.UserHome, name="UserHome"),
    path("user_view_data/", usr.user_view_data, name="user_view_data"),
    path("user_trainset/", usr.user_trainset, name="user_trainset"),
    path("user_testset/", usr.user_testset, name="user_testset"),
    path("user_prediction/", usr.user_prediction, name="user_prediction"),
    path("user_train_deep_learning/", usr.user_train_deep_learning, name="user_train_deep_learning"),
    path("analysis/", usr.analysis, name="analysis"),
    ### Admin Side Views
    path("AdminLoginCheck/", admins.AdminLoginCheck, name="AdminLoginCheck"),
    path("AdminHome/", admins.AdminHome, name="AdminHome"),
    path("ViewRegisteredUsers/", admins.ViewRegisteredUsers, name="ViewRegisteredUsers"),
    path("admin_forecast/", admins.admin_forecast, name="admin_forecast"),
    path("AdminActivaUsers/", admins.AdminActivaUsers, name="AdminActivaUsers"),

    # path("AdminDataPreProcess/", admins.AdminDataPreProcess, name="AdminDataPreProcess"),
]

users/forms.py
from django import forms
from .models import UserRegistrationModel


class UserRegistrationForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                           required=True, max_length=100)

    loginid = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[a-zA-Z]+', 'class': 'form-control'}),
                              required=True, max_length=100)

    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'pattern': '(?=.*\d)(?=.*[a-z])(?=.*[A-Z]).{8,}', 'class': 'form-control',
                                          'title': 'Must contain at least one number and one uppercase and lowercase letter, and at least 8 or more characters'}),
        required=True, max_length=100)

    mobile = forms.CharField(widget=forms.TextInput(attrs={'pattern': '[56789][0-9]{9}', 'class': 'form-control'}),
                             required=True,
                             max_length=100)

    email = forms.CharField(
        widget=forms.TextInput(attrs={'pattern': '[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$', 'class': 'form-control'}),
        required=True, max_length=100)

    locality = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), required=True, max_length=100)

    address = forms.CharField(widget=forms.Textarea(attrs={'rows': 3, 'cols': 20, 'class': 'form-control'}),
                              required=True, max_length=250)

    city = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    state = forms.CharField(widget=forms.TextInput(
        attrs={'autocomplete': 'off', 'pattern': '[A-Za-z ]+', 'title': 'Enter Characters Only ',
               'class': 'form-control'}), required=True,
        max_length=100)

    status = forms.CharField(widget=forms.HiddenInput(), initial='waiting', max_length=100)

    class Meta():
        model = UserRegistrationModel
        fields = '__all__'

assets/templates/AdminLogin.html
{% extends  'base.html' %}
{% load static %}

{% block title %}
    Admin Login
{% endblock %}
{% block admin_login %}
    active
{% endblock %}


{% block content %}
    <style>
        body {
            background: #e9ecef;
        }

        .jumbotron {
            font-family: "Book Antiqua";
        }

        .card {
            width: 40%;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        }

    </style>

    <center>
        <div class="jumbotron">
            <div class="container">
                <div class="card card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <form action="{% url 'AdminLoginCheck' %}" method="POST" class="text-primary">
                                {% csrf_token %}
                                <legend style="float: right">Admin</legend>
                                <br><br>

                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" name="loginid" required
                                               placeholder="Enter Login Id">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="password" class="form-control" name="pswd" required
                                               placeholder="Enter password">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <div class="col-md-12">

                                        <center>
                                            <input type="submit" class="btn btn-block btn-primary" value="Sign in">
                                            &nbsp;
                                            <input type="reset" class="btn btn-block btn-dark">
                                        </center>
                                    </div>
                                </div>


                                <!-- Message -->
                                {% if messages %}
                                    {% for message in messages %}
                                        <p align="center" class="text-primary"> {{ message }}</p>
                                    {% endfor %}
                                {% endif %}


                            </form>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </center>
{% endblock %}

assets/templates/UserLogin.html
{% extends 'base.html' %}
{% load static %}

{% block title %}User Login{% endblock %}
{% block user_login %}active{% endblock %}

{% block content %}


    <style>
        body {
            background: #e9ecef;
        }

        .jumbotron {
            font-family: "Book Antiqua";
        }

        .card {
            width: 40%;
            box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12), 0 1px 2px rgba(0, 0, 0, 0.24);
        }

    </style>
    <center>
        <div class="jumbotron">
            <div class="container">
                <div class="card card-body">
                    <div class="row">
                        <div class="col-md-12">

                            <form action="{% url 'UserLoginCheck' %}" method="POST" class="text-primary">
                                {% csrf_token %}

                                <legend style="float: right"> User </legend>

                                <br> <br>

                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="text" class="form-control" name="loginname" required
                                               placeholder="Enter Login Id">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-12">
                                        <input type="password" class="form-control" name="pswd" required
                                               placeholder="Enter password">
                                    </div>
                                </div>
                                <div class="form-group row">
                                    <div class="col-md-12">


                                        <input type="submit" class="btn btn-block btn-primary" value="Sign in"> &nbsp;
                                        <input type="reset" class="btn btn-block btn-dark">

                                    </div>
                                </div>


                                <!-- Message -->
                                {% if messages %}
                                    {% for message in messages %}
                                        <p align="center" class="text-primary"> {{ message }}</p>
                                    {% endfor %}
                                {% endif %}

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </center>
{% endblock %}

assets/templates/UserRegistrations.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    User Registration
{% endblock %}
{% block user_signup %}
    active
{% endblock %}
{% block content %}

    <style>
        .jumbotron {
            font-family: "Book Antiqua";
            text-align: center;
            background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),
            url("{% static 'main_static/img/slide/slide-1.jpg' %}") no-repeat center center fixed;
            background-size: cover;

        }
.body{
      background: linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)),
            url("{% static 'main_static/img/slide/slide-1.jpg' %}") no-repeat center center fixed;
            background-size: cover;
}
        .row {
            background: #e9ecef;

        }

        .card .card-body {
            background: transparent;
            border: none;
        }

    </style>

    <!--form -->
    <center>
        <div class="jumbotron">

            <div class="container">
                <div class="row card  card-body">
                    <form action="{% url 'UserRegisterActions' %}" method="POST">

                        {% csrf_token %}
                        <legend align="center" class="text-info"><strong>User Sign up</strong></legend>
                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="id_name">User Name</label>
                                {{ form.name }}
                            </div>

                            <div class="form-group col-md-4">
                                <label for="id_loginid">Login Id</label>
                                {{ form.loginid }}
                            </div>


                            <div class="form-group col-md-4">
                                <label for="id_email">Email</label>
                                {{ form.email }}
                            </div>

                            <div class="form-group col-md-4">
                                <label for="id_mobile">Mobile</label>
                                {{ form.mobile }}
                            </div>


                            <div class="form-group col-md-4">
                                <label for="id_password">Password</label>
                                {{ form.password }}
                            </div>


                            <div class="form-group col-md-4">
                                <label for="id_locality">Locality</label>
                                {{ form.locality }}
                            </div>

                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-4">
                                <label for="id_city">City</label>
                                {{ form.city }}
                            </div>

                            <div class="form-group col-md-4">

                            </div>
                            <div class="form-group col-md-4">
                                <label for="id_state">State</label>
                                {{ form.state }}
                            </div>
                            <div class="form-group col-md-2">
                                {#                            <label for="id_status">Status</label>#}
                                {{ form.status }}
                            </div>


                            <div class="form-group col-md-8">
                                <label for="id_address">Address </label>
                                {{ form.address }}

                            </div>


                        </div>


                        <button type="submit" class="btn btn-info">Sign up</button>
                        <button type="reset" class="btn btn-outline-dark">Reset</button>
                        <!-- Message -->
                        {% if messages %}
                            {% for message in messages %}
                                <p align="center" class="text-primary"> {{ message }}</p>
                            {% endfor %}
                        {% endif %}

                    </form>
                </div>
            </div>
        </div>
    </center>
{% endblock %}

assets/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-reboot.min.css' %}">


    <!-- from index.html-->

    <link href="{% static 'main_static/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'main_static/vendor/aos/aos.css' %}" rel="stylesheet">
    <link href="{% static 'main_static/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'main_static/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'main_static/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'main_static/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'main_static/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
    <link href="{% static 'main_static/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    <link href="{% static 'main_static/css/style.css' %}" rel="stylesheet">


</head>
<body>
<header id="header" class="fixed-top">
    <div class="container d-flex align-items-center justify-content-between">

        <h1 class="logo"><a href="/">Stock <span class="text-danger">Market</span> </a></h1>
        <!-- Uncomment below if you prefer to use an image logo -->
        <!--  <a href="index.html" class="logo"><img src="{% static 'main_static/img/logo.png' %}" alt="" class="img-fluid"></a> -->

        <nav id="navbar" class="navbar">
            <ul>
                <li><a class="nav-link scrollto {% block home %} {% endblock %} " href="/">Home</a></li>
                <li><a class="nav-link scrollto {% block user_login %} {% endblock %}" href="{% url 'UserLogin' %}">Users</a></li>
                <li><a class="nav-link scrollto {% block admin_login %} {% endblock %}" href="{% url 'AdminLogin' %}">Admin</a></li>

                <li><a class="getstarted scrollto" href="{% url 'UserRegister' %}"> Register</a></li>
            </ul>
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

    </div>
</header><!-- End Header -->
<!-- Header -->

<section>

    {% block content %}

    {% endblock %}
</section>
<!-- Footer -->
<footer id="footer">
    <div class="container">
        <div class="copyright">
            &copy; Copyright <strong><span>STOCK</span> MARKET</strong>. All Rights Reserved
        </div>
        <div class="credits">
            <!-- All the links in the footer should remain intact. -->
            <!-- You can delete the links only if you purchased the pro version. -->
            <!-- Licensing information: https://bootstrapmade.com/license/ -->
            <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/multi-responsive-bootstrap-template/ -->
            Designed by <a href="">Alex Corporation</a>
        </div>
    </div>
</footer><!-- End Footer -->


<script src="{% static 'js/bootstrap.bundle.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/bootstrap.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>
</html>